### ISSUE TITLE
H15 @ Cobro - Introducir código manualmente

### ISSUE THREAD

**Issue by quemasda** [quemasda/api-project#205]
- [ ] H15 @ Crear input númerico con separador (#200)
- [ ] H15 @ Maquetar formulario (#201)
- [ ] H15 @ Validar código (#202)
- [ ] H15 @ Maquetar vista `Efectivo solicitado` (#203)
- [ ] H15 @ Maquetar vista `Efectivo no solicitado` (#204)
