### ISSUE TITLE
H10 @ Deuda técnica

### ISSUE THREAD

**Issue by quemasda** [quemasda/api-project#208]
- [ ] H10 @ Error si la localización está desactivada (#206)
- [ ] H10 @ Cerrar la aplicación con la `X` (#207)
- [ ] Permitir documentos con menos de 8 dígitos (#176)
- [ ] Eliminar campo de cumpleaños (#177)
- [ ] Leer SMS con la clave (#178)
- [ ] Tests mapa (#179)
- [ ] Tests formulario `Tu negocio` (#180)
- [ ] Tests genoma_api (#181)
- [ ] Tests genoma_login (#182)
