### ISSUE TITLE
H15 @ Cobro - Introducir código manualmente

### ISSUE THREAD

**Issue by quemasda** [quemasda/api-project#339]
- [ ] H15 @ Crear input númerico con separador (#334)
- [ ] H15 @ Maquetar formulario (#335)
- [ ] H15 @ Validar código (#336)
- [ ] H15 @ Maquetar vista `Efectivo solicitado` (#337)
- [ ] H15 @ Maquetar vista `Efectivo no solicitado` (#338)
