### ISSUE TITLE
H10 @ Deuda técnica

### ISSUE THREAD

**Issue by quemasda** [quemasda/api-project#359]
- [ ] H10 @ Error si la localización está desactivada (#356)
- [ ] H10 @ Cerrar la aplicación con la `X` (#357)
- [ ] H10 @ Permitir documentos con menos de 8 dígitos (#358)
