### ISSUE TITLE
H10 @ Deuda técnica

### ISSUE THREAD

**Issue by quemasda** [quemasda/api-project#379]
- [ ] H10 @ Error si la localización está desactivada (#376)
- [ ] H10 @ Cerrar la aplicación con la `X` (#377)
- [ ] H10 @ Permitir documentos con menos de 8 dígitos (#378)
