### ISSUE TITLE
H10 @ Deuda técnica

### ISSUE THREAD

**Issue by quemasda** [quemasda/api-project#410]
- [ ] H10 @ Error si la localización está desactivada (#407)
- [ ] H10 @ Cerrar la aplicación con la `X` (#408)
- [ ] H10 @ Permitir documentos con menos de 8 dígitos (#409)
